version: 2.1

jobs:
    build-medium-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/mpld3
    steps:
      
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
            uname -m
            sudo apt-get update && sudo apt-get --allow-downgrades install python3 python3-pip 
            sudo apt-get install libpq-dev --allow-downgrades libxml2-dev --allow-downgrades libxslt1-dev --allow-downgrades python3-dev --allow-downgrades
            sudo apt-get install gcc-aarch64-linux-gnu --allow-downgrades
            sudo apt-get install -y npm
            python3 -m pip install backports.zoneinfo
            python3 -m pip install --upgrade pip wheel setuptools tox 
            python3 -m pip install --upgrade pip 
            npm install deck.gl 
            pip3 install pydeck pandas pytest 
            cd bindings/pydeck 
            pytest
                
                    
workflows:
  version: 2
  python3.7:
    jobs:

      - build-medium-arm64 
