name: test

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.1/install.sh | bash
          nvm install 12.12.0 && nvm use 12.12.0
          cd bindings/pydeck
          make setup-env
          make init

      - name: Run tests
        run: |
          cd bindings/pydeck
          make test

  armv64_py37_job:
      name: Build and Test for arm64 with py37
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install python3.7 curl git && \
              ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && export DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata && dpkg-reconfigure --frontend noninteractive tzdata && \
              apt-get -y install software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt-get -y update && \
              apt install -y python3.7-venv && python3.7 -m venv venv37 && source venv37/bin/activate && \
              python3.7 -m pip install --upgrade pip && \
              python3.7 --version && \
              uname -m && \
              whoami && \
              pwd && \
              ls && \
              apt-get install -y npm && \
              npm install deck.gl && \
              python3.7 -m pip install --upgrade pip && \
              cd bindings/pydeck/requirements && \
              pyhon3.7 -m pip install pydeck  && \
              pyhon3.7 -m pip install pydeck pandas pytest && \
              pyhon3.7 -m pip install -r requirements-dev.txt && \
              curl https://raw.github.com/creationix/nvm/master/install.sh | sh && \
              nvm install 10.16.0 && \
              nvm use 10.16.0 && \
              cd .. && \
              pyhon3.7 -m pip install -e . --install-option "--build_all" && \
              pyhon3.7 -m pip install -e . --install-option "--build_all" --verbose && \
              pyhon3.7 -m pip install pydeck  && \
              pyhon3.7 -m pytest --cov=pydeck && \
              deactivate'
              
  armv64_job:
    name: Build and Test for arm64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Install and Run tests
        run: |
           docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
             arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install git python3 python3-pip yarn && apt-get -y install curl && \
              ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && export DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata && dpkg-reconfigure --frontend noninteractive tzdata && \
              apt-get install -y mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6 && apt-get install -y npm && \
              python3 -m pip install --upgrade pip && \
              npm install deck.gl && \
              pip3 install --upgrade pip && \
              cd bindings/pydeck/requirements && \
              pip3 install --upgrade pip && \
              pip3 install pydeck  && \
              pip 3install -r requirements-dev.txt && \
              pip3 install pydeck pandas pytest && \
              curl https://raw.github.com/creationix/nvm/master/install.sh | sh && \
              nvm install 10.16.0 && \
              nvm use 10.16.0 && \
              cd .. && \
              pip install -e . --install-option "--build_all" && \
              pip install -e . --install-option "--build_all" --verbose && \
              pip3 install pydeck pandas pytest && \
              pytest --cov=pydeck && \
              deactivate'
